Repository inTestiGator/pytest-blame, pull requests merged in 2019-04, with the labels that each got.

#16 changed orange python badge to blue
  README.md
Labels: Urgent!, bug, enhancement, help wanted

#22 Add Sample File and Sample Test File, Implement Codecov
  sample.py
  tests/test_sample.py
Labels: Bugfix, test

#24 Test Case for Current Conftest
  pytest.ini
  pytest_blame.py
  tests/conftest.py
  tests/test_blame.py
  tests/test_conftest.py
Labels: test

#26 Implement Getstatus to Collect Status Checks from CI
  getstatus.py
  tests/conftest.py
Labels: new feature

#34 Feature/dynamic slug
  tests/conftest.py
Labels: new feature

#36 Fixed a Bug That Function Contains Unnecessary Code
  tests/conftest.py
Labels: bug
